name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Zip source files
      run: zip -r app.zip .

    - name: Upload to S3
      uses: aws-actions/s3-sync-action@v0.5.0
      with:
        args: --acl public-read
        source: '.'
        destination: 's3://my-deployment-bucket-devops-proj2'

    - name: Deploy with CodeDeploy
      uses: aws-actions/aws-codedeploy-action@v0.2.0
      with:
        application-name: MyFlaskAppDeployment
        deployment-group-name: MyFlaskAppGroup
        bucket: my-deployment-bucket
        key: app.zip
        bundle-type: zip