name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Zip source files
      run: zip -r app.zip .

    - name: Upload to S3
      run: |
        aws s3 cp app.zip s3://my-deployment-bucket-devops-proj2-radv/app.zip --acl public-read

    - name: Deploy with AWS CLI
      run: |
        aws deploy create-deployment \
          --application-name MyFlaskAppDeployment \
          --deployment-group-name MyFlaskAppGroup \
          --s3-location bucket=my-deployment-bucket-devops-proj2,key=app.zip,bundleType=zip
