name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Zip source files
      run: zip -r app.zip .

    - name: Upload to S3
      uses: aws-actions/aws-s3-sync@v2
      with:
        source: .
        destination: s3://my-deployment-bucket

    - name: Deploy with CodeDeploy
      uses: aws-actions/aws-codedeploy-deploy@v1
      with:
        application-name: MyFlaskAppDeployment
        deployment-group-name: MyFlaskAppGroup
        bucket: my-deployment-bucket
        key: app.zip
